### ISSUE TITLE
Car settings 

### ISSUE THREAD

**Issue by InaJ123** [DIT112-V21/group-03#29]
As a user I want to be able to adjust the Smart pet buddys’ default settings

Acceptance criteria: 

- The app should have a section in Profile page where the user can change different settings

- The user can edit settings and the Smart pet buddys’ behaviour will change accordingly

**Comment by emilieanthony** [comment]
This user story will not be worked since we made design choices that makes it redundant. We agreed that specific car settings in the profile would not be necessary as the user can change for example mode view (race mode/ manual mode/ auto mode) and speed in direct connection to the features in the app. However, if the app scales and more functionalities are added, we might re-open this issue.
